sudo: required
language: java
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
  - $HOME/.m2
      
script: mvn test -B

before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
 
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
after_script:
  - cat target/surefire-reports/TestSuite.txt
  
notifications:
  email:
    recipients:
      - ashkan@binary.com
      - mohammad@binary.com
      - bijan@binary.com
      - ridho@binary.com
      - ehtesham@binary.com
      - munsei@binary.com
      - negar@binary.com
      - kelly@binary.com
    on_success: never
    on_failure: always